### ISSUE TITLE
Change service invocation examples to use native language http client in combination with Dapr's http proxy capability 

### ISSUE THREAD

**Issue by greenie-msft** [amulyavarote/dapr-quickstarts-examples#1]
We are of the opinion that for service invocation, languages should leverage Dapr's http or gRPC proxying capabilities in combination with native http or gRPC client code. 

This issue is to switch the service invocation examples from using the SDK's invoke methods (which use Dapr's service invocation API) to http / gRPC proxying capabilities which leverage native http grpc client code

**Comment by amulyavarote** [comment]
@greenie-msft Can we have more discussion on this?

**Comment by amulyavarote** [comment]
Pushed requested changes.
