### ISSUE TITLE
Add components directory into repo

### ISSUE THREAD

**Issue by greenie-msft** [amulyavarote/dapr-quickstarts-examples#2]
We should be explicit about which components are used in this repo instead of relying on the components that are installed when initializing a Dapr environment.

Solution - create a components directory in the repo and pass the components-path to the `dapr run` command so it loads the components defined in the repo.

**Comment by amulyavarote** [comment]
Added components folder to the project.

**Comment by amulyavarote** [comment]
Hence, closing this issue.
