### ISSUE TITLE
Switch RabbitMQ message queue to use the default Redis instance

### ISSUE THREAD

**Issue by greenie-msft** [amulyavarote/dapr-quickstarts-examples#3]
Even though RabbitMQ is more representative of a real world application using a real message queue, we should limit the amount of dependencies a customer needs to install and configure in order to run a quickstart. 

We should switch out the rabbitMQ component (which is defined in the commands file) for an actual component yaml file for redis

**Comment by amulyavarote** [comment]
PR is merged!
